# Generated by Django 5.2.5 on 2025-09-20 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalreport',
            name='report_type',
            field=models.CharField(choices=[('mammogram', 'Mammogram')], default='mammogram', max_length=20),
        ),
    ]
