# Generated by Django 5.2.5 on 2025-09-20 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_medicalreport_report_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalreport',
            name='grad_cam_image',
            field=models.ImageField(blank=True, null=True, upload_to='grad_cam_images/'),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='patient_id',
            field=models.CharField(blank=True, help_text='Patient unique identifier', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='medicalreport',
            name='report_name',
            field=models.CharField(blank=True, help_text='Name/identifier for this report', max_length=255, null=True),
        ),
    ]
